CREATE OR REPLACE VIEW GOLD.VW_DELAY_CATEGORY_SUMMARY AS
SELECT
    DELIVERY_DELAY_CATEGORY,

    COUNT(*) AS TOTAL_ORDERS,

    ROUND(AVG(DELIVERY_DELAY), 2) AS AVG_DELAY,
    ROUND(AVG(DELIVERY_RATING), 2) AS AVG_RATING,

    ROUND(
        COUNT(*) / SUM(COUNT(*)) OVER (),
    2) AS PERCENT_SHARE

FROM GOLD.FACT_DELIVERY
GROUP BY DELIVERY_DELAY_CATEGORY;