CREATE OR REPLACE VIEW GOLD.VW_DELIVERY_PERSON_SUMMARY AS
SELECT
    dp.DELIVERY_PERSON_NAME,
    dp.EMPLOYMENT_TYPE,
    dp.VEHICLE_TYPE,

    COUNT(*) AS TOTAL_DELIVERIES,

    ROUND(AVG(d.DELIVERY_DELAY), 2) AS AVG_DELAY,
    ROUND(AVG(d.DELIVERY_RATING), 2) AS AVG_RATING,

    ROUND(
        COUNT_IF(d.DELIVERY_DELAY_CATEGORY = 'ON TIME') * 100
        / NULLIF(COUNT(*), 0),
    2) AS ON_TIME_RATE

FROM GOLD.FACT_DELIVERY d
JOIN GOLD.DIM_DELIVERY_PERSON dp
    ON d.DELIVERY_PERSON_ID = dp.DELIVERY_PERSON_ID

GROUP BY 
    dp.DELIVERY_PERSON_NAME,
    dp.EMPLOYMENT_TYPE,
    dp.VEHICLE_TYPE;


SELECT * FROM GOLD.VW_DELIVERY_PERSON_SUMMARY;