CREATE OR REPLACE VIEW GOLD.VW_DELIVERY_SUMMARY AS
SELECT
    ORDER_DATE,

    COUNT(*) AS TOTAL_ORDERS,

    ROUND(AVG(DELIVERY_DELAY), 2) AS AVG_DELAY,
    ROUND(AVG(DELIVERY_RATING), 2) AS AVG_RATING,

    ROUND(
        COUNT_IF(DELIVERY_DELAY_CATEGORY = 'ON TIME') * 100
        / NULLIF(COUNT(*), 0),
    2) AS ON_TIME_RATE,

    ROUND(
        COUNT_IF(DELIVERY_DELAY_CATEGORY != 'ON TIME') * 100
        / NULLIF(COUNT(*), 0),
    2) AS DELAY_RATE

FROM GOLD.FACT_DELIVERY
GROUP BY ORDER_DATE;

SELECT * FROM GOLD.VW_DELIVERY_SUMMARY;