CREATE OR REPLACE VIEW GOLD.VW_FULFILLMENT_SUMMARY AS
SELECT
    f.SERVICE_LEVEL,
    f.SHIPPING_METHOD,

    COUNT(*) AS TOTAL_ORDERS,

    ROUND(AVG(d.DELIVERY_DELAY), 2) AS AVG_DELAY,
    ROUND(AVG(d.DELIVERY_RATING), 2) AS AVG_RATING,

    ROUND(
        COUNT_IF(d.DELIVERY_DELAY_CATEGORY = 'ON TIME')
        / NULLIF(COUNT(*), 0),
    2) AS ON_TIME_RATE

FROM GOLD.FACT_DELIVERY d
JOIN GOLD.DIM_FULFILLMENT f
    ON d.FULFILLMENT_ID = f.FULFILLMENT_ID

GROUP BY f.SERVICE_LEVEL, f.SHIPPING_METHOD;