ecomerce_dbt:
  outputs:
    dev:
      account: 
      database: ECOMMERCE
      password: 
      role: ACCOUNTADMIN
      schema: LANDING
      threads: 1
      type: snowflake
      user: 
      warehouse: COMPUTE_WH
  target: dev
