CREATE OR REPLACE VIEW GOLD.VW_CAMPAIGN_PERFORMANCE AS
SELECT
    dc.CAMPAIGN_NAME,
    dc.CAMPAIGN_TYPE,
    dc.OBJECTIVE,

    COUNT(DISTINCT fs.ORDER_ID) AS TOTAL_ORDERS,

    ROUND(AVG(fs.DISCOUNT_PERCENTAGE),2) AS AVG_DISCOUNT_PERCENTAGE

FROM GOLD.FACT_SALES fs
LEFT JOIN GOLD.DIM_CAMPAIGN dc
    ON fs.CAMPAIGN_ID = dc.CAMPAIGN_ID

GROUP BY
    dc.CAMPAIGN_NAME,
    dc.CAMPAIGN_TYPE,
    dc.OBJECTIVE;


SELECT *
FROM GOLD.VW_CAMPAIGN_PERFORMANCE;