CREATE OR REPLACE VIEW GOLD.VW_CUSTOMER_INSIGHTS AS
SELECT
    dc.CUSTOMER_ID,
    dc.FULL_NAME,
    dc.GENDER,
    dc.AGE_GROUP,
    dc.INCOME_BRACKET,
    dc.MARITAL_STATUS,

    dl.CITY,
    dl.STATE,
    dl.REGION,

    COUNT(DISTINCT fs.ORDER_ID) AS TOTAL_ORDERS,
    SUM(fs.ORDER_VALUE) AS TOTAL_SPENT,
    ROUND(AVG(fs.ORDER_VALUE),2) AS AVG_ORDER_VALUE,

    SUM(fs.REFUND_AMOUNT) AS TOTAL_REFUND,

    MAX(fs.ORDER_DATE) AS LAST_PURCHASE_DATE

FROM GOLD.FACT_SALES fs
LEFT JOIN GOLD.DIM_CUSTOMER dc
    ON fs.CUSTOMER_ID = dc.CUSTOMER_ID

LEFT JOIN GOLD.DIM_LOCATION dl
    ON dc.LOCATION_ID = dl.LOCATION_ID

GROUP BY
    dc.CUSTOMER_ID,
    dc.FULL_NAME,
    dc.GENDER,
    dc.AGE_GROUP,
    dc.INCOME_BRACKET,
    dc.MARITAL_STATUS,
    dl.CITY,
    dl.STATE,
    dl.REGION;

SELECT *
FROM GOLD.VW_CUSTOMER_INSIGHTS;