CREATE OR REPLACE VIEW GOLD.VW_FULFILLMENT_INSIGHTS AS
SELECT
    df.SHIPPING_METHOD,
    df.SERVICE_LEVEL,
    df.DELIVERY_SLA_DAYS,

    COUNT(DISTINCT fs.ORDER_ID) AS TOTAL_ORDERS,

    SUM(df.BASE_SHIPPING_COST) AS SHIPPING_REVENUE

FROM GOLD.FACT_SALES fs
LEFT JOIN GOLD.DIM_FULFILLMENT df
    ON fs.FULFILLMENT_ID = df.FULFILLMENT_ID

GROUP BY
    df.SHIPPING_METHOD,
    df.SERVICE_LEVEL,
    df.DELIVERY_SLA_DAYS;


SELECT *
FROM GOLD.VW_FULFILLMENT_INSIGHTS;