CREATE OR REPLACE VIEW GOLD.VW_LOCATION_INSIGHTS AS
SELECT
    dl.CITY,
    dl.STATE,
    dl.REGION,
    dl.AREA_TYPE,

    COUNT(DISTINCT fs.ORDER_ID) AS TOTAL_ORDERS,

    SUM(fs.ORDER_VALUE) AS TOTAL_REVENUE,

    ROUND(AVG(fs.ORDER_VALUE),2) AS AVG_ORDER_VALUE,

    SUM(fs.REFUND_AMOUNT) AS TOTAL_REFUND

FROM GOLD.FACT_SALES fs
LEFT JOIN GOLD.DIM_LOCATION dl
    ON fs.LOCATION_ID = dl.LOCATION_ID

GROUP BY
    dl.CITY,
    dl.STATE,
    dl.REGION,
    dl.AREA_TYPE;


SELECT *
FROM GOLD.VW_LOCATION_INSIGHTS;