CREATE OR REPLACE VIEW GOLD.VW_ORDER_STATUS_SUMMARY AS
SELECT
    ORDER_STATUS,

    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
    
FROM GOLD.FACT_SALES

GROUP BY ORDER_STATUS;


SELECT *
FROM GOLD.VW_ORDER_STATUS_SUMMARY;