CREATE OR REPLACE VIEW GOLD.VW_PAYMENT_ANALYSIS AS
SELECT
    dpay.PAYMENT_METHOD,
    dpay.PAYMENT_PROVIDER,

    COUNT(DISTINCT fs.ORDER_ID) AS TOTAL_ORDERS

FROM GOLD.FACT_SALES fs
LEFT JOIN GOLD.DIM_PAYMENT dpay
    ON fs.PAYMENT_ID = dpay.PAYMENT_ID

GROUP BY
    dpay.PAYMENT_METHOD,
    dpay.PAYMENT_PROVIDER;



SELECT *
FROM GOLD.VW_PAYMENT_ANALYSIS;


