CREATE OR REPLACE VIEW GOLD.VW_PRODUCT_PERFORMANCE AS
SELECT
    dp.PRODUCT_ID,
    dp.PRODUCT_NAME,
    dp.CATEGORY,
    dp.SUB_CATEGORY,
    dp.BRAND,
    dp.PRICE,

    COUNT(DISTINCT fs.ORDER_ID) AS TOTAL_ORDERS,
    SUM(fs.QUANTITY) AS TOTAL_QUANTITY_SOLD,

    SUM(fs.GROSS_AMOUNT) AS GROSS_REVENUE,
    SUM(fs.ORDER_VALUE) AS NET_REVENUE,

    SUM(fs.REFUND_AMOUNT) AS REFUND_AMOUNT,

    ROUND(
        SUM(fs.ORDER_VALUE) / NULLIF(SUM(fs.QUANTITY), 0),
        2
    ) AS AVG_SELLING_PRICE

FROM GOLD.FACT_SALES fs
LEFT JOIN GOLD.DIM_PRODUCT dp
    ON fs.PRODUCT_ID = dp.PRODUCT_ID

GROUP BY
    dp.PRODUCT_ID,
    dp.PRODUCT_NAME,
    dp.CATEGORY,
    dp.SUB_CATEGORY,
    dp.BRAND,
    dp.PRICE;


SELECT *
FROM GOLD.VW_PRODUCT_PERFORMANCE;