CREATE OR REPLACE VIEW GOLD.VW_SALES_PERFORMANCE AS
SELECT
    fs.ORDER_DATE,
    dp.CATEGORY,
    dp.SUB_CATEGORY,
    dp.BRAND,

    COUNT(DISTINCT fs.ORDER_ID) AS TOTAL_ORDERS,
    SUM(fs.QUANTITY) AS TOTAL_QUANTITY_SOLD,

    SUM(fs.GROSS_AMOUNT) AS GROSS_REVENUE,
    SUM(fs.DISCOUNT_AMOUNT) AS TOTAL_DISCOUNT,

    SUM(fs.ORDER_VALUE) AS NET_REVENUE,

    SUM(fs.REFUND_AMOUNT) AS TOTAL_REFUND,

    SUM(fs.ORDER_VALUE) - SUM(fs.REFUND_AMOUNT) AS FINAL_REVENUE

FROM GOLD.FACT_SALES fs
LEFT JOIN GOLD.DIM_PRODUCT dp
    ON fs.PRODUCT_ID = dp.PRODUCT_ID

GROUP BY
    fs.ORDER_DATE,
    dp.CATEGORY,
    dp.SUB_CATEGORY,
    dp.BRAND;


SELECT * 
FROM GOLD.VW_SALES_PERFORMANCE;