CREATE OR REPLACE VIEW GOLD.VW_FEEDBACK_SUMMARY AS
SELECT
    ORDER_DATE,

    COUNT(*) AS TOTAL_REVIEWS,

    ROUND(AVG(CUSTOMER_RATING), 2) AS AVG_CUSTOMER_RATING,
    ROUND(AVG(SELLER_RATING), 2) AS AVG_SELLER_RATING,
    ROUND(AVG(SENTIMENT_SCORE), 2) AS AVG_SENTIMENT_SCORE

FROM GOLD.FACT_FEEDBACK
GROUP BY ORDER_DATE;


SELECT * FROM GOLD.VW_FEEDBACK_SUMMARY;