CREATE OR REPLACE VIEW GOLD.VW_SENTIMENT_CATEGORY_SUMMARY AS
SELECT
    SENTIMENT_CATEGORY,

    COUNT(*) AS TOTAL_REVIEWS,

    ROUND(
        COUNT(*) * 100 / SUM(COUNT(*)) OVER (),
    2) AS PERCENT_SHARE,

    ROUND(AVG(CUSTOMER_RATING), 2) AS AVG_CUSTOMER_RATING

FROM GOLD.FACT_FEEDBACK
GROUP BY SENTIMENT_CATEGORY;


SELECT * FROM GOLD.VW_SENTIMENT_CATEGORY_SUMMARY;