CREATE OR REPLACE VIEW GOLD.VWSESSION__CUSTOMER_SEGMENTATION AS
SELECT
    c.AGE_GROUP,
    c.INCOME_BRACKET,
    c.GENDER,

    COUNT(DISTINCT f.CUSTOMER_ID) AS TOTAL_CUSTOMERS,
    COUNT(f.SESSION_ID) AS TOTAL_SESSIONS,

    SUM(f.PURCHASES) AS TOTAL_PURCHASES,

    ROUND(SUM(f.IS_CONVERTED)*100 / COUNT(f.SESSION_ID),2) AS CONVERSION_RATE

FROM GOLD.FACT_SESSION f
JOIN GOLD.DIM_CUSTOMER c
    ON f.CUSTOMER_ID = c.CUSTOMER_ID
GROUP BY c.AGE_GROUP, c.INCOME_BRACKET, c.GENDER;

SELECT * FROM GOLD.VWSESSION__CUSTOMER_SEGMENTATION;