CREATE OR REPLACE VIEW GOLD.VW_SESSION_SESSION__FUNNEL_ANALYSIS AS
SELECT
    MONTHNAME(SESSION_DATE) AS MONTH_NAME,

    SUM(PRODUCT_VIEWS) AS PRODUCT_VIEWS,
    SUM(ADD_TO_CART_COUNT) AS ADD_TO_CART,
    SUM(CHECKOUT_ATTEMPTS) AS CHECKOUT,
    SUM(PURCHASES) AS PURCHASES,

    ROUND(SUM(ADD_TO_CART_COUNT)*100 / NULLIF(SUM(PRODUCT_VIEWS),0),2) AS VIEW_TO_CART_RATE,
    ROUND(SUM(CHECKOUT_ATTEMPTS) / NULLIF(SUM(ADD_TO_CART_COUNT),0),2) AS CART_TO_CHECKOUT_RATE,
    ROUND(SUM(PURCHASES) / NULLIF(SUM(CHECKOUT_ATTEMPTS),0),2) AS CHECKOUT_TO_PURCHASE_RATE

FROM GOLD.FACT_SESSION
GROUP BY MONTH_NAME;


SELECT * FROM GOLD.VW_SESSION_SESSION__FUNNEL_ANALYSIS;
