CREATE OR REPLACE VIEW GOLD.VW_SESSION_KPI_SUMMARY AS
SELECT
    MONTHNAME(SESSION_DATE) AS MONTH_NAME,

    COUNT(DISTINCT SESSION_ID) AS TOTAL_SESSIONS,
    COUNT(DISTINCT CUSTOMER_ID) AS UNIQUE_CUSTOMERS,

    SUM(PAGE_VIEWS) AS TOTAL_PAGE_VIEWS,
    SUM(PRODUCT_VIEWS) AS TOTAL_PRODUCT_VIEWS,

    SUM(ADD_TO_CART_COUNT) AS TOTAL_CART_ADDS,
    SUM(CHECKOUT_ATTEMPTS) AS TOTAL_CHECKOUTS,
    SUM(PURCHASES) AS TOTAL_PURCHASES,

    ROUND(SUM(IS_CONVERTED) * 100 / COUNT(SESSION_ID),2) AS CONVERSION_RATE,

    ROUND(AVG(SESSION_DURATION_IN_SEC),2) AS AVG_SESSION_DURATION

FROM GOLD.FACT_SESSION
GROUP BY MONTH_NAME;

SELECT * FROM GOLD.VW_SESSION_KPI_SUMMARY