CREATE OR REPLACE VIEW GOLD.VW_SESSION__CHANNEL_PERFORMANCE AS
SELECT
    ch.CHANNEL_NAME,
    ch.CHANNEL_TYPE,

    COUNT(f.SESSION_ID) AS TOTAL_SESSIONS,
    SUM(f.PURCHASES) AS TOTAL_PURCHASES,

    ROUND(SUM(f.IS_CONVERTED)*100 / COUNT(f.SESSION_ID),2) AS CONVERSION_RATE,

    ROUND(AVG(f.SESSION_DURATION_IN_SEC),2) AS AVG_SESSION_DURATION

FROM GOLD.FACT_SESSION f
JOIN GOLD.DIM_CHANNEL ch
    ON f.CHANNEL_ID = ch.CHANNEL_ID
GROUP BY ch.CHANNEL_NAME, ch.CHANNEL_TYPE;

SELECT * FROM VW_SESSION__CHANNEL_PERFORMANCE