-- Email Masking Policy
CREATE OR REPLACE MASKING POLICY email_mask_policy
AS (val STRING)
RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'SECURITYADMIN') THEN val
        ELSE REGEXP_REPLACE(val, '(^.).*(@.*$)', '\\1*****\\2')
    END;


-- Phone Number Masking Policy
CREATE OR REPLACE MASKING POLICY phone_mask_policy
AS (val STRING)
RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'SECURITYADMIN') THEN val
        ELSE CONCAT('XXXXXX', RIGHT(val, 4))
    END;


-- Credit Card Masking Policy
CREATE OR REPLACE MASKING POLICY credit_card_mask_policy
AS (val STRING)
RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'SECURITYADMIN') THEN val
        ELSE CONCAT('XXXXXXXXXXXX', RIGHT(val, 4))
    END;


-- UPI ID Masking Policy
CREATE OR REPLACE MASKING POLICY upi_mask_policy
AS (val STRING)
RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'SECURITYADMIN') THEN val
        ELSE REGEXP_REPLACE(val, '^(.{2}).*(@.*)$', '\\1******\\2')
    END;


-- Bank Account Number Masking Policy
CREATE OR REPLACE MASKING POLICY bank_account_mask_policy
AS (val STRING)
RETURNS STRING ->
CASE
    WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'SECURITYADMIN') THEN val
    ELSE CONCAT('XXXXXXXX', RIGHT(val, 4))
END;


-- IFSC Code Masking Policy
CREATE OR REPLACE MASKING POLICY ifsc_mask_policy
AS (val STRING)
RETURNS STRING ->
CASE
    WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'SECURITYADMIN') THEN val
    ELSE CONCAT(LEFT(val, 4), 'XXX')
END;



-- DIM CUSTOMER MASKING POLICY

ALTER TABLE ECOMMERCE.GOLD.DIM_CUSTOMER
MODIFY COLUMN EMAIL
SET MASKING POLICY email_mask_policy;

ALTER TABLE ECOMMERCE.GOLD.DIM_CUSTOMER
MODIFY COLUMN PHONE_NUMBER
SET MASKING POLICY phone_mask_policy;

ALTER TABLE ECOMMERCE.GOLD.DIM_CUSTOMER
MODIFY COLUMN CREDIT_CARD_NUMBER
SET MASKING POLICY credit_card_mask_policy;

ALTER TABLE ECOMMERCE.GOLD.DIM_CUSTOMER
MODIFY COLUMN UPI_ID
SET MASKING POLICY upi_mask_policy;


SELECT * FROM ECOMMERCE.GOLD.DIM_CUSTOMER;



-- DIM DELIVERY PERSON MASKING POLICY

ALTER TABLE ECOMMERCE.GOLD.DIM_DELIVERY_PERSON
MODIFY COLUMN PHONE_NUMBER
SET MASKING POLICY phone_mask_policy;

SELECT * FROM ECOMMERCE.GOLD.DIM_DELIVERY_PERSON;



-- DIM SELLER PERSON MASKING POLICY

ALTER TABLE ECOMMERCE.GOLD.DIM_SELLER
MODIFY COLUMN PHONE_NUMBER
SET MASKING POLICY phone_mask_policy;


ALTER TABLE ECOMMERCE.GOLD.DIM_SELLER
MODIFY COLUMN EMAIL
SET MASKING POLICY email_mask_policy;


ALTER TABLE ECOMMERCE.GOLD.DIM_SELLER
MODIFY COLUMN IFSC_CODE
SET MASKING POLICY ifsc_mask_policy;


ALTER TABLE ECOMMERCE.GOLD.DIM_SELLER
MODIFY COLUMN BANK_ACCOUNT_NUMBER
SET MASKING POLICY bank_account_mask_policy;

SELECT * FROM ECOMMERCE.GOLD.DIM_SELLER;



-- FACT SALES PERSON MASKING POLICY

ALTER TABLE ECOMMERCE.GOLD.FACT_SALES
MODIFY COLUMN PAYMENT_DETAILS
SET MASKING POLICY credit_card_mask_policy;

ALTER TABLE ECOMMERCE.GOLD.FACT_SALES
MODIFY COLUMN PAYMENT_ID
SET MASKING POLICY bank_account_mask_policy;

ALTER TABLE ECOMMERCE.GOLD.FACT_SALES
MODIFY COLUMN CUSTOMER_ID
SET MASKING POLICY bank_account_mask_policy;

SELECT * FROM ECOMMERCE.GOLD.FACT_SALES;