CREATE OR REPLACE FILE FORMAT ECOM_RAW_CSV
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
TRIM_SPACE = TRUE
EMPTY_FIELD_AS_NULL = TRUE
NULL_IF = ('', 'NULL')
COMPRESSION = 'AUTO'; 

ALTER FILE FORMAT ECOMMERCE.LANDING.ECOM_RAW_CSV SET ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE




