CREATE OR REPLACE PIPE ECOMMERCE.LANDING.ECOM_SNOWPIPE_ORDER AUTO_INGEST = TRUE AS
COPY INTO ECOMMERCE.LANDING.RAW_ORDER 
FROM @ECOMMERCE.LANDING.ECOMMERCE_S3_EXT_STAGE/raw_orders/ 
FILE_FORMAT = ECOMMERCE.LANDING.ECOM_RAW_CSV;

CREATE OR REPLACE PIPE ECOM_SNOWPIPE_RAW_MARKETINGS AUTO_INGEST = TRUE AS
COPY INTO ECOMMERCE.LANDING.RAW_MARKETING
FROM '@ECOMMERCE_S3_EXT_STAGE/raw_marketing/' 
FILE_FORMAT = ECOM_RAW_CSV;

ALTER PIPE ECOMMERCE.LANDING.ECOM_SNOWPIPE_ORDER REFRESH;
ALTER PIPE ECOM_SNOWPIPE_RAW_MARKETINGS REFRESH;

SELECT * FROM RAW_ORDER;
SELECT * FROM RAW_MARKETING;


