CREATE OR REPLACE STORAGE INTEGRATION S3_ECOM_INT_STAGE
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = S3
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN ='arn:aws:iam::346826929170:role/Ecoomrce-data-role' 
STORAGE_ALLOWED_LOCATIONS =('s3://ecoomerce-data/');

DESC INTEGRATION S3_ECOM_INT_STAGE;


CREATE OR REPLACE STAGE ECOMMERCE_S3_EXT_STAGE
URL ='s3://ecoomerce-data'
file_format = ECOM_RAW_CSV
storage_integration = S3_ECOM_INT_STAGE;

LIST @ECOMMERCE_S3_EXT_STAGE;



DROP STAGE ECOMMERCE_S3_STAGE;


DROP INTEGRATION IF EXISTS S3_INT_NEW;


