CREATE OR REPLACE VIEW GOLD.VW_MARKETING_KPI AS
SELECT
    MONTHNAME(EVENT_DATE) AS MONTH_NAME,

    SUM(IMPRESSIONS) AS TOTAL_IMPRESSIONS,
    SUM(CLICKS) AS TOTAL_CLICKS,
    SUM(CONVERSIONS) AS TOTAL_CONVERSIONS,

    SUM(SPEND_AMOUNT) AS TOTAL_SPEND,
    SUM(REVENUE_GENERATED) AS TOTAL_REVENUE,

    ROUND(SUM(CLICKS)*100 / NULLIF(SUM(IMPRESSIONS),0), 2) AS CTR,
    ROUND(SUM(CONVERSIONS)*100 / NULLIF(SUM(CLICKS),0), 2) AS CONVERSION_RATE,
    ROUND(SUM(SPEND_AMOUNT)*100 / NULLIF(SUM(CONVERSIONS),0), 2) AS CPA,
    ROUND(SUM(REVENUE_GENERATED)*100 / NULLIF(SUM(SPEND_AMOUNT),0), 2) AS ROAS

FROM GOLD.FACT_MARKETING
GROUP BY MONTH_NAME;

SELECT * FROM  GOLD.VW_MARKETING_KPI;

