CREATE OR REPLACE VIEW GOLD.VW_MARKETING_CAMPAIGN_PERFORMANCE AS
SELECT
    c.CAMPAIGN_NAME,
    c.CAMPAIGN_TYPE,
    c.OBJECTIVE,

    COUNT(DISTINCT m.EVENT_DATE) AS ACTIVE_DAYS,

    SUM(m.IMPRESSIONS) AS IMPRESSIONS,
    SUM(m.CLICKS) AS CLICKS,
    SUM(m.CONVERSIONS) AS CONVERSIONS,

    SUM(m.SPEND_AMOUNT) AS SPEND,
    SUM(m.REVENUE_GENERATED) AS REVENUE,

    ROUND(SUM(m.CLICKS)*100 / NULLIF(SUM(m.IMPRESSIONS),0), 2) AS CTR,
    ROUND(SUM(m.CONVERSIONS)*100 / NULLIF(SUM(m.CLICKS),0), 2) AS CVR,
    ROUND(SUM(m.REVENUE_GENERATED)*100 / NULLIF(SUM(m.SPEND_AMOUNT),0), 2) AS ROAS

FROM GOLD.FACT_MARKETING m
JOIN GOLD.DIM_CAMPAIGN c
    ON m.CAMPAIGN_ID = c.CAMPAIGN_ID
GROUP BY c.CAMPAIGN_NAME, c.CAMPAIGN_TYPE, c.OBJECTIVE;


SELECT * FROM GOLD.VW_MARKETING_CAMPAIGN_PERFORMANCE;