CREATE OR REPLACE VIEW GOLD.VW_MARKETING_GEO_PERFORMANCE AS
SELECT
    STATE,
    CITY,

    SUM(IMPRESSIONS) AS IMPRESSIONS,
    SUM(CLICKS) AS CLICKS,
    SUM(CONVERSIONS) AS CONVERSIONS,

    SUM(REVENUE_GENERATED) AS REVENUE,
    SUM(SPEND_AMOUNT) AS SPEND,

    ROUND(SUM(CONVERSIONS)*100 / NULLIF(SUM(CLICKS),0), 2) AS CVR,
    ROUND(SUM(REVENUE_GENERATED)*100 / NULLIF(SUM(SPEND_AMOUNT),0), 2) AS ROAS

FROM GOLD.FACT_MARKETING
GROUP BY STATE, CITY;

SELECT * FROM GOLD.VW_MARKETING_GEO_PERFORMANCE;